### ISSUE TITLE
Opencv Android version??????

### ISSUE THREAD

**Issue by anthonyyuan** [predkambrij/eyeMon#1]
I want to know which version u used!!!!!!!!

**Comment by predkambrij** [comment]
Hi ?!?!?!?!?!?!?!?!?1111
You can see from https://github.com/predkambrij/eyeMon/blob/master/AndroidManifest.xml
that I used minSdkVersion 14 which means Android version 4.0.0 or larger https://en.wikipedia.org/wiki/Android_version_history

Right now I'm preparing Docerfile to easily build the apk.
Br.
