### ISSUE TITLE
How do  I run it

### ISSUE THREAD

**Issue by anthonyyuan** [predkambrij/eyeMon#2]
please tell me step step  ,but when i run it ,some error apear

**Comment by predkambrij** [comment]
Do you mean running on your computer? There is a section "Running the code on your computer" and there are 3 steps in total. https://github.com/predkambrij/eyeMon
Currently the thing is packaged using Docker with X11 socket sharing or ssh X forwarding for graphical interface. Hence it might be difficult to run the thing on other environments than Linux, although it's not entirely impossible :)
